name: "Mixed linter and checks"

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'main'

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: filter
        with:
          filters: |
            clang-format:
              - '**.c'
              - '**.h'
              - '**.in'
              - '**.inc'
              - '.github/workflows/lint.yml'
              - 'sys/clang-format.py'
              - '.clang-format'

  clang-format:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install wget, software-properties-common, lsb-release (dependencies of LLVM install script)
        run: sudo apt --assume-yes install wget software-properties-common lsb-release

      - name: Install automatic LLVM 16
        run: wget https://apt.llvm.org/llvm.sh -O /tmp/llvm-install.sh; chmod +x /tmp/llvm-install.sh; sudo /tmp/llvm-install.sh 16

      - name: Install clang-format-16
        run: sudo apt --assume-yes install clang-format-16

      - name: Install gitpython
        run: sudo pip install gitpython

      - name: Run clang-format
        run: |
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-16 160
          clang-format --version
          python sys/clang-format.py --check --verbose

  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4